/* Copyright (C) 2015  Rafał Ostanek
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.netbeans.lutece.freemarker.panel;

import org.openide.util.NbPreferences;

public final class FTLPanel extends javax.swing.JPanel {

    private final FTLOptionsPanelController controller;

    FTLPanel(FTLOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        embeddedMime = new javax.swing.JComboBox();
        labelEmbeddedLanguage = new javax.swing.JLabel();
        labelDebug = new javax.swing.JLabel();
        checkBoxDebug = new javax.swing.JCheckBox();

        embeddedMime.setEditable(true);
        embeddedMime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "text/html", "text/css", "text/javascript", "text/plain" }));

        org.openide.awt.Mnemonics.setLocalizedText(labelEmbeddedLanguage, org.openide.util.NbBundle.getMessage(FTLPanel.class, "FTLPanel.labelEmbeddedLanguage.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(labelDebug, org.openide.util.NbBundle.getMessage(FTLPanel.class, "FTLPanel.labelDebug.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(checkBoxDebug, org.openide.util.NbBundle.getMessage(FTLPanel.class, "FTLPanel.checkBoxDebug.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelDebug)
                    .addComponent(labelEmbeddedLanguage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(embeddedMime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxDebug))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmbeddedLanguage)
                    .addComponent(embeddedMime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDebug)
                    .addComponent(checkBoxDebug))
                .addContainerGap(120, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    void load() {
        embeddedMime.setSelectedItem(NbPreferences.forModule(FTLPanel.class).get("embeddedMime", "text/html"));
        checkBoxDebug.setSelected(NbPreferences.forModule(FTLPanel.class).getBoolean("debug", true));
    }

    void store() {
        NbPreferences.forModule(FTLPanel.class).put("embeddedMime", (String) embeddedMime.getSelectedItem());
        NbPreferences.forModule(FTLPanel.class).putBoolean("debug", checkBoxDebug.isSelected());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBoxDebug;
    private javax.swing.JComboBox embeddedMime;
    private javax.swing.JLabel labelDebug;
    private javax.swing.JLabel labelEmbeddedLanguage;
    // End of variables declaration//GEN-END:variables
}
